/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.5.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.configuration;


import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.http.HttpHeaders;
import org.springframework.web.reactive.function.client.WebClient;


public abstract class HttpInterfacesAbstractConfigurator {

    protected WebClient webClient;
    protected final HttpHeaders headers = new HttpHeaders();
    protected final ObjectMapper mapper = new ObjectMapper().findAndRegisterModules();

    public HttpInterfacesAbstractConfigurator() {
    }

}
