/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.5.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.configuration;

import org.openapitools.api.BookApi;
import org.openapitools.api.UserApi;

import org.springframework.context.annotation.Bean;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.support.WebClientAdapter;
import org.springframework.web.service.invoker.HttpServiceProxyFactory;

public abstract class HttpInterfacesAbstractConfigurator {

    private final WebClient webClient;

    public HttpInterfacesAbstractConfigurator(final WebClient webClient) {
        this.webClient = webClient;
    }

    @Bean(name = "org.openapitools.configuration.HttpInterfacesAbstractConfigurator.book")
    BookApi bookHttpProxy() {
        HttpServiceProxyFactory factory = HttpServiceProxyFactory.builder(WebClientAdapter.forClient(webClient)).build();
        return factory.createClient(BookApi.class);
    }

    @Bean(name = "org.openapitools.configuration.HttpInterfacesAbstractConfigurator.user")
    UserApi userHttpProxy() {
        HttpServiceProxyFactory factory = HttpServiceProxyFactory.builder(WebClientAdapter.forClient(webClient)).build();
        return factory.createClient(UserApi.class);
    }


}
