/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.5.0).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.configuration;

import org.openapitools.api.BookApi;
import org.openapitools.api.UserApi;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.http.HttpHeaders;
import org.springframework.context.annotation.Bean;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.support.WebClientAdapter;
import org.springframework.web.service.invoker.HttpServiceProxyFactory;

public abstract class HttpInterfacesAbstractConfigurator {

    protected WebClient webClient;
    protected final HttpHeaders headers = new HttpHeaders();
    protected final ObjectMapper mapper = new ObjectMapper().findAndRegisterModules();

    public HttpInterfacesAbstractConfigurator() {
    }

}
